spring:
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pohodeui70}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/pos}
  jpa:
    hibernate: 
      ddl-auto: update

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 30
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:1761/eureka}